#!/usr/bin/env ruby

CWD = File.dirname(__FILE__)

def handle_ltx(src)
  mfile = src.sub(/\.ltx/, ".md")
  hfile = src.sub(/\.ltx/, ".html")
  # abort "#{mfile} is newer than #{src}! Aborting" if File.mtime(mfile) > File.mtime(src)
# cmd = "cat #{src} | ruby #{CWD}/livetext.rb"
  cmd = "ruby #{CWD}/livetext.rb #{src}"
  system(cmd)
end

# Main

def clean_all
  files = Dir["*.ltx"]
  outfiles = []
  files.each do |file|
    f2 = file.sub(/.ltx$/, ".html")
    outfiles << f2 if File.exist?(f2) #  && File.mtime(f2) > File.mtime(file)
  end
  puts "Cleaning: #{outfiles.inspect}"
  system("rm -f #{outfiles.join(' ')}")
end

###

if ARGV.first == "--clean-all"
  clean_all
  exit
end

# abort "Need a file parameter" unless ARGV.first

src = ARGV.first

case
  when src =~ /.ltx$/
    handle_ltx(src)
  else
    abort "Unknown file extension"
end

