#!/usr/bin/env ruby

abort "Usage: runtests [all | unit | snapshots | parser | standard | html]" unless ARGV.first

arg, arg2 = ARGV

# all
#   unit
#     standard
#     parser
#       string
#       misc
#       set
#   snapshot

case arg
  when "all"
    system("ruby test/all.rb")
  when "unit"
    system("ruby test/unit/all.rb")
  when "parser"
    system("ruby test/unit/parser/all.rb")
  when "standard"
    system("ruby test/unit/standard.rb")
  when "html"
    system("ruby test/unit/html.rb")
  when "snapshots"
    puts "ruby test/snapshots.rb #{arg2}"
    system("ruby test/snapshots.rb #{arg2}")
else
  puts "Don't know #{arg}"
end
