#!/usr/bin/env ruby

system("vi lib/livetext/version.rb +/VER")

require 'date'
require "livetext"

today = Date.today.strftime("%Y-%m-%d")
version = Livetext::VERSION

system("git pull")
gs = `git status 2>&1`

puts gs

