#!/usr/bin/env ruby

def sys(str)
  ret = system str
  puts "  Failed: #{str}" unless ret
end

arg = ARGV.first

info = `gem list | grep livetext`
vrx  = /\((.*)\)/
version = vrx.match(info).to_a[1]

### FIXME!!!
# lib = "/Users/Hal/.rvm/gems/ruby-2.7.0/gems/livetext-#{version}/lib/"
puts
puts "  Copying repo to gem at: #{lib.inspect}"

sys("cp -r lib/* #{lib}/")
sys("cp plugin/misc/* #{lib}/../plugin/misc/*")
sys("cp plugin/*rb #{lib}/../plugin/")
sys("cp imports/*rb #{lib}/../imports/")
sys("cp -r test/* #{lib}/../test/")
sys("cp bin/* #{lib}/../bin/")

puts
