#!/usr/bin/env ruby

def sys(str)
  ret = system str
  puts "  Failed: #{str}" unless ret
end

arg = ARGV.first

if arg
  version = arg
else
  ret = system("livetext -v >/tmp/livetext.version 2>/tmp/livetext.version.error")
  raise "Malformed version number? #{version.inspect}" unless ret
end

lib = "/Users/Hal/.rvm/gems/ruby-2.7.0/gems/livetext-#{version}/lib/"
puts
puts "  Copying repo to gem at: #{lib.inspect}"

sys("cp -r lib/* #{lib}/")
sys("cp plugin/* #{lib}/../plugin/")
sys("cp imports/* #{lib}/../imports/")
sys("cp -r test/* #{lib}/../test/")
sys("cp bin/* #{lib}/../bin/")

puts
